name: solana_wallets_flutter
description: A flutter plugin to connect to a users wallet like phantom, solflare, etc.
version: 1.0.0
homepage: https://github.com/EPNW/solana_wallets_flutter

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.3
  inject_js: ^2.0.0
  flutter_svg: ^1.0.3
  meta: ^1.7.0
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/loader.js
